Repository Brandon-999/4806_project, pull requests merged in 2023-03, with the labels that each got.

#24 Feature/add user model and user repository files
  src/main/java/main/model/OrderModel.java
  src/main/java/main/model/UserModel.java
  src/main/java/main/repository/UserRepository.java
Labels: feature

#28 Feature/add OrdeModel and OrdeRepository
  src/main/java/main/model/OrderModel.java
  src/main/java/main/repository/OrderRepository.java
Labels: feature

#29 Feature/add shopping cart model and shopping cart repository
  src/main/java/main/model/ShoppingCartModel.java
  src/main/java/main/repository/ShoppingCartRepository.java
Labels: feature

#30 Feature/updating repos to use jpa
  src/main/java/main/BookStoreApp.java
  src/main/java/main/model/OrderModel.java
  src/main/java/main/model/ShoppingCartModel.java
  src/main/java/main/model/UserModel.java
  src/main/java/main/repository/BookRepository.java
  src/main/java/main/repository/OrderRepository.java
  src/main/java/main/repository/ShoppingCartRepository.java
  src/main/java/main/repository/UserRepository.java
Labels: bug, enhancement, feature

#31 Update README.md
  README.md
Labels: enhancement

#34 Controller Implementation of Log-in/Register
  src/main/java/main/controller/BookStoreController.java
  src/main/java/main/controller/CartController.java
  src/main/java/main/controller/GUIController.java
  src/main/java/main/service/UserService.java
  src/main/java/main/service/UserServiceImpl.java
Labels: feature

#38 Added quantity tracking to ShoppingCartModel & OrderModel
  src/main/java/main/model/OrderModel.java
  src/main/java/main/model/ShoppingCartModel.java
Labels: enhancement

#44 Feature/add testing to model classes
  src/test/java/main/model/BookModelTest.java
  src/test/java/main/model/BookStoreModelTest.java
  src/test/java/main/model/OrderModelTest.java
  src/test/java/main/model/ShoppingCartModelTest.java
  src/test/java/main/model/UserModelTest.java
Labels: feature

#50 Fixed error where it would allow the user to login with incorrect password
  src/main/java/main/controller/BookStoreController.java
  src/main/java/main/service/UserService.java
  src/main/java/main/service/UserServiceImpl.java
Labels: enhancement

#53 Feature/service additional checks
  src/main/java/main/service/UserService.java
  src/main/java/main/service/UserServiceImpl.java
Labels: feature

#60 Fix verifyLogin function
  src/main/java/main/service/UserServiceImpl.java
Labels: bug

#61 Feature/connect project to my sql database
  Dockerfile
  README.md
  docker-compose.yml
  pom.xml
  src/main/resources/application.properties
Labels: feature

#68 Added a shopping cart to the UserModel constructor that is used for user registeration.
  src/main/java/main/controller/CartController.java
  src/main/java/main/model/UserModel.java
  src/main/java/main/repository/UserRepository.java
  src/test/java/main/model/UserModelTest.java
Labels: feature

#69 Fixed Bugs with last push, Books now show up in front page again
  src/main/java/main/controller/BookStoreController.java
  src/main/java/main/controller/CartController.java
  src/main/resources/application.properties
Labels: feature

#70 Feature/checkout service
  pom.xml
  src/main/java/main/controller/CartController.java
  src/main/java/main/service/UserService.java
  src/main/java/main/service/UserServiceImpl.java
Labels: feature

#73 Add files via upload
  UML_Diagram.png
Labels: documentation

#72 Add files via upload
  ER-Diagram.png
Labels: documentation

#74 Added UML and ER diagrams to readme
  README.md
Labels: documentation

#46 Feature/smoke test and application test
  .github/workflows/maven-tests.yml
  pom.xml
  src/main/java/main/model/Credentials.java
  src/test/java/main/BookStoreAppTest.java
  src/test/java/main/EndpointsTest.java
Labels: feature

#83 added fixture test for login/register inputs
  jasmine/SpecRunner.html
  jasmine/lib/jquery-3.6.4.js
  jasmine/spec/testSpec.js
Labels: enhancement

#84 Verify credentials on requests that access or modify user data
  src/main/java/main/controller/BookStoreController.java
  src/main/java/main/controller/CartController.java
  src/main/java/main/model/Credentials.java
  src/main/resources/static/javascript/book.js
  src/main/resources/static/javascript/cart.js
  src/main/resources/static/javascript/common.js
  src/main/resources/static/javascript/order.js
  src/test/java/main/EndpointsTest.java
Labels: Security
