Repository Brandon-999/4806_project, pull requests merged in 2023-04, with the labels that each got.

#90 Feature/add book search and sort
  src/main/java/main/model/BookModel.java
  src/main/java/main/service/BookService.java
  src/main/resources/static/images/cart.png
  src/main/resources/static/images/cart2.png
  src/main/resources/static/images/pride_and_prejudice.jpg
  src/main/resources/static/images/the_alchemist.jpg
  src/main/resources/static/images/the_catcher_in_the_rye.jpg
  src/main/resources/static/images/the_count_of_monte_cristo.jpg
  src/main/resources/static/images/the_girl_with_the_dragon_tattoo.jpg
  src/main/resources/static/images/the_great_gatsby.jpg
  src/main/resources/static/images/the_hitchhiker's_guide_to_the_galaxy.jpg
  src/main/resources/static/images/the_hunger_games.jpg
  src/main/resources/static/images/the_lord_of_the_rings.jpg
  src/main/resources/static/images/the_road.jpg
  src/main/resources/static/images/to_kill_a_mockingbird.jpg
  src/main/resources/static/javascript/DataTables-1.13.4/images/sort_asc.png
  src/main/resources/static/javascript/DataTables-1.13.4/images/sort_asc_disabled.png
  src/main/resources/static/javascript/DataTables-1.13.4/images/sort_both.png
  src/main/resources/static/javascript/DataTables-1.13.4/images/sort_desc.png
  src/main/resources/static/javascript/DataTables-1.13.4/images/sort_desc_disabled.png
  src/main/resources/static/javascript/DataTables-1.13.4/js/dataTables.bootstrap.min.js
  src/main/resources/static/javascript/DataTables-1.13.4/js/dataTables.bootstrap5.min.js
  src/main/resources/static/javascript/DataTables-1.13.4/js/dataTables.bulma.min.js
  src/main/resources/static/javascript/DataTables-1.13.4/js/dataTables.dataTables.min.js
  src/main/resources/static/javascript/DataTables-1.13.4/js/dataTables.foundation.min.js
  src/main/resources/static/javascript/DataTables-1.13.4/js/dataTables.jqueryui.min.js
  src/main/resources/static/javascript/DataTables-1.13.4/js/dataTables.semanticui.min.js
  src/main/resources/static/javascript/DataTables-1.13.4/js/jquery.dataTables.min.js
  src/main/resources/static/javascript/book.js
  src/main/resources/static/javascript/cart.js
  src/main/resources/static/javascript/common.js
  src/main/resources/static/javascript/datatables.min.js
  src/main/resources/static/javascript/index.js
  src/main/resources/static/javascript/jQuery-3.6.0/jquery-3.6.0.min.js
  src/main/resources/static/javascript/order.js
  src/main/resources/static/stylesheets/book.css
  src/main/resources/static/stylesheets/common.css
  src/main/resources/static/stylesheets/datatables.min.css
  src/main/resources/static/stylesheets/index.css
  src/main/resources/templates/cart.html
  src/main/resources/templates/index.html
  src/main/resources/templates/order.html
  src/test/java/main/EndpointsTest.java
  src/test/java/main/model/BookModelTest.java
  src/test/java/main/model/OrderModelTest.java
  src/test/java/main/model/ShoppingCartModelTest.java
Labels: feature

#91 Feature/add jaccard book recommendations
  src/main/java/main/controller/BookStoreController.java
  src/main/java/main/model/UserModel.java
  src/main/java/main/repository/UserRepository.java
  src/main/java/main/service/UserService.java
  src/main/java/main/service/UserServiceImpl.java
  src/main/resources/static/javascript/common.js
  src/main/resources/static/javascript/index.js
  src/main/resources/static/stylesheets/index.css
  src/main/resources/templates/index.html
  src/test/java/main/EndpointsTest.java
Labels: feature

#94 Add stock feature
  src/main/java/main/controller/CartController.java
  src/main/java/main/model/BookModel.java
  src/main/java/main/service/BookService.java
  src/main/java/main/service/UserService.java
  src/main/java/main/service/UserServiceImpl.java
  src/main/resources/static/javascript/book.js
  src/main/resources/templates/book.html
  src/test/java/main/EndpointsTest.java
  src/test/java/main/model/BookModelTest.java
  src/test/java/main/model/OrderModelTest.java
  src/test/java/main/model/ShoppingCartModelTest.java
Labels: feature

#89 Implement "Add book" page
  coverImages/1984.jpg
  coverImages/farenheit_451.jpg
  coverImages/pride_and_prejudice.jpg
  coverImages/the_alchemist.jpg
  coverImages/the_catcher_in_the_rye.jpg
  coverImages/the_count_of_monte_cristo.jpg
  coverImages/the_girl_with_the_dragon_tattoo.jpg
  coverImages/the_great_gatsby.jpg
  coverImages/the_hitchhiker's_guide_to_the_galaxy.jpg
  coverImages/the_hunger_games.jpg
  coverImages/the_lord_of_the_rings.jpg
  coverImages/the_mist.jpg
  coverImages/the_road.jpg
  coverImages/to_kill_a_mockingbird.jpg
  src/main/java/main/controller/BookStoreController.java
  src/main/java/main/controller/GUIController.java
  src/main/java/main/model/BookModel.java
  src/main/java/main/service/BookService.java
  src/main/resources/application.properties
  src/main/resources/static/images/book_cover_not_found.png
  src/main/resources/static/images/cart2.png
  src/main/resources/static/javascript/book.js
  src/main/resources/static/javascript/common.js
  src/main/resources/static/stylesheets/addBook.css
  src/main/resources/templates/addBook.html
  src/main/resources/templates/book.html
  src/test/java/main/EndpointsTest.java
  src/test/java/main/model/BookModelTest.java
  src/test/java/main/model/OrderModelTest.java
  src/test/java/main/model/ShoppingCartModelTest.java
Labels: feature

#100 Fixed EndpointTests bug causing visual inconsistencies.
  .github/workflows/maven-tests.yml
  README.md
  docker-compose.yml
  src/main/resources/application.test.properties
  src/main/resources/init/create_test_db.sql
  src/test/java/main/EndpointsTest.java
Labels: bug

#102 Fixed Jaccard Distance Recommendations to not repeat the same book more than once
  src/main/java/main/service/UserServiceImpl.java
  src/main/resources/static/javascript/common.js
Labels: bug

#104 Update CSS to prevent overflow.
  src/main/resources/static/stylesheets/common.css
Labels: bug

#105 Uploaded ER and UML diagrams
  ER-Diagram-M3.png
  UML_Diagram_M3.png
Labels: documentation

#106 Update README with new Diagrams for M3
  README.md
Labels: documentation

#108 added the intialize admin function to create an admin user when the application is started
  src/main/java/main/service/BookService.java
Labels: enhancement

#107 Added admin login to README
  README.md
Labels: documentation

#109 fixed readme admin credentials to look better and increase visibility.
  README.md
Labels: documentation
